# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s15ftgb196-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/a_summer_xilinx/catmario_1/catmario_1.cache/wt [current_project]
set_property parent.project_path E:/a_summer_xilinx/catmario_1/catmario_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/a_summer_xilinx/catmario_1/RGB2DVI_IP [current_project]
update_ip_catalog
set_property ip_output_repo e:/a_summer_xilinx/catmario_1/catmario_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/a_summer_xilinx/catmario_1/baw_unknown_Picture_R_Rom.coe
add_files E:/a_summer_xilinx/catmario_1/wholergb_cat_Picture_R_Rom.coe
add_files E:/a_summer_xilinx/catmario_1/wholergb_cat_Picture_G_Rom.coe
add_files E:/a_summer_xilinx/catmario_1/wholergb_cat_Picture_B_Rom.coe
add_files E:/a_summer_xilinx/catmario_1/baw_brick_Picture_R_Rom.coe
add_files E:/a_summer_xilinx/catmario_1/baw_hidden_Picture_R_Rom.coe
add_files E:/a_summer_xilinx/catmario_1/baw_win_Picture_R_Rom.coe
add_files E:/a_summer_xilinx/catmario_1/baw_fail_Picture_R_Rom.coe
add_files E:/a_summer_xilinx/catmario_1/monster1_Picture_R_Rom.coe
add_files E:/a_summer_xilinx/catmario_1/monster1_Picture_G_Rom.coe
add_files E:/a_summer_xilinx/catmario_1/monster1_Picture_B_Rom.coe
add_files E:/a_summer_xilinx/catmario_1/caw_monster_Picture_R_Rom.coe
add_files E:/a_summer_xilinx/catmario_1/caw_monster_Picture_G_Rom.coe
add_files E:/a_summer_xilinx/catmario_1/caw_monster_Picture_B_Rom.coe
read_verilog -library xil_defaultlib {
  E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/new/Driver_HDMI.v
  E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/new/key2move.v
  E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/new/monster.v
  E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/new/state.v
  E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/new/video.v
  E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/new/HDMI_display.v
}
read_ip -quiet E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/unknown_dist_mem_gen_0/unknown_dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/unknown_dist_mem_gen_0/unknown_dist_mem_gen_0_ooc.xdc]

read_ip -quiet E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/brick_dist_mem_gen_0/brick_dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/brick_dist_mem_gen_0/brick_dist_mem_gen_0_ooc.xdc]

read_ip -quiet E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/catr_dist_mem_gen_0/catr_dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/catr_dist_mem_gen_0/catr_dist_mem_gen_0_ooc.xdc]

read_ip -quiet E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/catg_dist_mem_gen_0/catg_dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/catg_dist_mem_gen_0/catg_dist_mem_gen_0_ooc.xdc]

read_ip -quiet E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/catb_dist_mem_gen_0/catb_dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/catb_dist_mem_gen_0/catb_dist_mem_gen_0_ooc.xdc]

read_ip -quiet E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
set_property used_in_implementation false [get_files -all e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc]

read_ip -quiet E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/hidden_dist_mem_gen_0/hidden_dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/hidden_dist_mem_gen_0/hidden_dist_mem_gen_0_ooc.xdc]

read_ip -quiet E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/win_dist_mem_gen_0/win_dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/win_dist_mem_gen_0/win_dist_mem_gen_0_ooc.xdc]

read_ip -quiet E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/fail_dist_mem_gen_0/fail_dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/fail_dist_mem_gen_0/fail_dist_mem_gen_0_ooc.xdc]

read_ip -quiet E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/monsterr_dist_mem_gen_0/monsterr_dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/monsterr_dist_mem_gen_0/monsterr_dist_mem_gen_0_ooc.xdc]

read_ip -quiet E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/monsterg_dist_mem_gen_0/monsterg_dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/monsterg_dist_mem_gen_0/monsterg_dist_mem_gen_0_ooc.xdc]

read_ip -quiet E:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/monsterb_dist_mem_gen_0/monsterb_dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/monsterb_dist_mem_gen_0/monsterb_dist_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/a_summer_xilinx/catmario_1/catmario_1.srcs/constrs_1/new/system.xdc
set_property used_in_implementation false [get_files E:/a_summer_xilinx/catmario_1/catmario_1.srcs/constrs_1/new/system.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top HDMI_display -part xc7s15ftgb196-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef HDMI_display.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file HDMI_display_utilization_synth.rpt -pb HDMI_display_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
