# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/catr_dist_mem_gen_0/catr_dist_mem_gen_0.xci
# IP: The module: 'catr_dist_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/catr_dist_mem_gen_0/catr_dist_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'catr_dist_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/catr_dist_mem_gen_0/catr_dist_mem_gen_0.xci
# IP: The module: 'catr_dist_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/a_summer_xilinx/catmario_1/catmario_1.srcs/sources_1/ip/catr_dist_mem_gen_0/catr_dist_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'catr_dist_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
